FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# Copier tous les fichiers y compris le Maven wrapper
COPY . .

# Rendre le wrapper exécutable
RUN chmod +x ./mvnw

# Builder l'application
RUN ./mvnw package -DskipTests

# Exposer le port
EXPOSE 8080

# Lancer l'application
ENTRYPOINT ["java", "-jar", "target/eval-0.0.1-SNAPSHOT.jar"]
